version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      # Install Docker Compose
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      # Build and run the services
      - run:
          name: Build and Run Docker Compose
          command: docker-compose up --build -d

      # Run your tests here
      - run:
          name: Run Tests
          command: docker-compose exec chatroom-app npm test

      # Tear down the services
      - run:
          name: Tear Down Docker Compose
          command: docker-compose down

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
