version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    working_directory: ~/project/chatroom-app
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Установка Node.js и зависимостей
          command: |
            echo "Installing Node.js version and dependencies..."
            node --version
            npm --version
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Проверка структуры проекта
          command: ls -R src/components
      - run:
          name: Сборка проекта
          command: npm run build
      - run:
          name: Создание директории артефактов
          command: mkdir -p ~/artifacts
      - run:
          name: Копирование артефактов
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

workflows:
  build:
    jobs:
      - build-node
