version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker Compose
          command: |
            mkdir -p $HOME/.docker/cli-plugins
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o $HOME/.docker/cli-plugins/docker-compose
            chmod +x $HOME/.docker/cli-plugins/docker-compose
            echo 'export PATH=$HOME/.docker/cli-plugins:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build Docker images
          command: |
            docker-compose -f docker-compose.yml build
      - run:
          name: Push Docker images to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker-compose -f docker-compose.yml push
      - run:
          name: Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
