version: 2.1

jobs:
  build:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker images
          command: |
            docker-compose -f docker-compose.yml build
      - run:
          name: Push Docker images to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker-compose -f docker-compose.yml push
      - run:
          name: Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
